### ISSUE TITLE
跟CoordinatorLayout一起用的时候滑动冲突

### ISSUE THREAD

**Issue by lewiswon** [canyinghao/CanRefresh#9]
当Toolbar设置了layout_scrollFlags="scroll|enterAlways"，刚开始向下滑动的时候会有卡顿，但是滑过header的高度后就正常了

**Comment by canyinghao** [comment]
确实有这问题，暂时没能解决。

**Comment by lewiswon** [comment]
是否跟behavior有关系？

**Comment by canyinghao** [comment]
应该是吧，我暂时也没时间弄。你可以试着修复一下。

**Comment by lewiswon** [comment]
我监听了AppBarLayout的offset change，在offset!=0的时候，让canChildScrollUp返回true，暂时解决了这个问题，我看到你项目中也有相关的代码，但是好像只适用于CanRefreshLayout作为CoordinatorLayout的父布局。

**Comment by canyinghao** [comment]
嗯，我只是让CoordinatorLayout作为子视图时可刷新。
